[package]
name = "ptr_eq-macro"
version = "0.1.0"
authors = ["Shaoyuan Chen <chensy20@mails.tsinghua.edu.cn>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"